feat: add checks for export and import

diff --git a/move-wsl b/move-wsl
--- a/move-wsl
+++ b/move-wsl
@@ -24,11 +24,26 @@ fi
 echo "Exporting VHDX to \"$TEMP_FILE\" ..."
 wsl --export $WSL_NAME $TEMP_FILE
 
+if [ ! -f $TEMP_FILE ]; then
+    echo "ERROR: Export failed. $TEMP_FILE does not exist."
+    exit 2
+fi
+
 echo "Unregistering WSL ..."
 wsl --unregister $WSL_NAME &>/dev/null
 
 echo "Importing \"$WSL_NAME\" at \"$WSL_TARGET\" ..."
 wsl --import $WSL_NAME $WSL_TARGET $TEMP_FILE
+
+if [ -z $(wsl --list | iconv -f UTF-16LE -t UTF-8 | grep -E "(^|\s)$WSL_NAME($|\s)") ]; then
+    echo "ERROR: Import failed. Distro not found. Export file at $TEMP_FILE"
+    exit 3
+fi
+
+if [ ! -f "$WSL_TARGET/ext4.vhdx" ]; then
+    echo "ERROR: Import failed. Target file not found. Export file at $TEMP_FILE"
+    exit 4
+fi
 
 echo "Cleaning up ..."
 rm $TEMP_FILE
